### ISSUE TITLE
Python-Modul mbus lädt nicht

### ISSUE THREAD

**Issue by kptkip** [dnoermann/Homeautomation#1]
Hallo Dennis,

ich versuche das Skript zum Auslesen meines Wärmemengenzählers zu nutzen.

Obwohl ich zwei ("MBus" und "pyMeterBus") Mbus-module in python installiert habe erhalte ich folgenden Fehler:

`ImportError: cannot import name 'MBus' from 'mbus' (/home/pi/.local/lib/python3.11/site-packages/mbus/__init__.py)`

**Comment by dnoermann** [comment]
Du brauchst http://www.rscada.se/libmbus und python-mbus https://github.com/rscada/python-mbus

**Comment by kptkip** [comment]
Hallo Dennis,

hab die beiden Bibliotheken installiert - ersteres sogar selbst kompiliert - da die 64Bit-Version auf meinem Raspi nicht lief (ist ne 32-Version).

Jetzt kommt aber trotzdem folgendes:
```
Traceback (most recent call last):
  File "/home/pi/ReadHRIDataUnitMBus.py", line 16, in <module>
    from mbus.MBus import MBus
ModuleNotFoundError: No module named 'mbus.MBus'
```

Wenn ich mir per `pip3 list` die Module anzeigen lasse, gibt es auch nur ein Modul `mbus`

Gruß Alex

**Comment by kptkip** [comment]
Bin einen Schritt weiter - die MOdule laden ;-)

jetzt kommt die nächste Meldung:

```Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/mbus-0.0.1-py3.11.egg/mbus/MBus.py", line 66, in __init__
  File "/usr/local/lib/python3.11/dist-packages/mbus-0.0.1-py3.11.egg/mbus/MBusLowLevel.py", line 199, in __init__
  File "/usr/lib/python3.11/ctypes/__init__.py", line 389, in __getattr__
    func = self.__getitem__(name)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 394, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: /usr/local/lib/libmbus.so.0: undefined symbol: mbus_get_current_version

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/home/pi/ReadHRIDataUnitMBus.py", line 21, in <module>
    mbus = MBus(device=usbdevice)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mbus-0.0.1-py3.11.egg/mbus/MBus.py", line 68, in __init__
OSError: libmbus not found
Exception ignored in: <function MBus.__del__ at 0x75f72528>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/mbus-0.0.1-py3.11.egg/mbus/MBus.py", line 97, in __del__
AttributeError: 'MBus' object has no attribute 'handle'
```
Wenn ich die mitgelieferte Testscripte nutze kommt Folgendes:

```
mbus-serial-request-data -d  /dev/serial0 0
[2023-12-15 21:20:34] SEND (005): 10 5B 00 5B 16
Failed to receive M-Bus response frame.
```
Es sieht also so aus, als ob das device nicht richtig arbeitet. Ich sehe auchauf dem MBus-Hat auch keine der RX/TX-LEDs leuchten.

Allerdings kommt die 35v-Spannung am MBUS-Modul am Zähler an (habs gemessen) und am Zähler wird unter der Ebene Ebene 6 / Modulschleife: 06-01 folgendes Angezeigt: `MOD 9`

Ist das korrekt so?

Gruß Alex

**Comment by kptkip** [comment]
kleine Korrektur:
`mbus-serial-request-data -d  -b 2400 /dev/serial0 0`

ergibt folgendes:
```
[2023-12-15 22:14:30] SEND (005): 10 5B 00 5B 16
[2023-12-15 22:14:31] RECV (185): 68 B3 B3 68 08 00 72 00 14 65 30 C5 14 00 04 05 00 00 00 04 78 08 B4 D3 01 04 06 1B 07 00 00 04 13 B8 0F 08 00 04 2B D3 0A 00 00 14 2B 9E 52 00 00 04 3B 32 04 00 00 14 3B A5 0B 00 00 02 5B 20 00 02 5F 1E 00 02 61 DF 00 02 23 37 01 04 6D 0C 37 EF 2C 44 06 00 00 00 00 44 13 00 00 00 00 42 6C 00 00 01 FD 17 40 03 FD 0C 05 00 00 84 20 06 00 00 00 00 C4 20 06 00 00 00 00 84 30 06 00 00 00 00 C4 30 06 00 00 00 00 84 40 13 01 00 00 00 C4 40 13 00 00 00 00 84 80 40 13 01 00 00 00 C4 80 40 13 00 00 00 00 84 C0 40 13 01 00 00 00 C4 C0 40 13 00 00 00 00 86 16
mbus_frame_print: Dumping M-Bus frame [type 4, 185 bytes]: 68 B3 B3 68 08 00 72 00 14 65 30 C5 14 00 04 05 00 00 00 04 78 08 B4 D3 01 04 06 1B 07 00 00 04 13 B8 0F 08 00 04 2B D3 0A 00 00 14 2B 9E 52 00 00 04 3B 32 04 00 00 14 3B A5 0B 00 00 02 5B 20 00 02 5F 1E 00 02 61 DF 00 02 23 37 01 04 6D 0C 37 EF 2C 44 06 00 00 00 00 44 13 00 00 00 00 42 6C 00 00 01 FD 17 40 03 FD 0C 05 00 00 84 20 06 00 00 00 00 C4 20 06 00 00 00 00 84 30 06 00 00 00 00 C4 30 06 00 00 00 00 84 40 13 01 00 00 00 C4 40 13 00 00 00 00 84 80 40 13 01 00 00 00 C4 80 40 13 00 00 00 00 84 C0 40 13 01 00 00 00 C4 C0 40 13 00 00 00 00 86 16 
mbus_frame_print: Dumping M-Bus frame [type 1995841608, -3 bytes]: 
Segmentation fault
```

Das heißt doch, dass da was ankommt, oder?

**Comment by kptkip** [comment]
Hab das ganze nun per shell-script,  http://www.rscada.se/libmbus und Mosquitto gelöst.

Klappt nun sauber.

Danke für die Anregungen :-)
Gruß Alex

**Comment by kptkip** [comment]
s.o.
